GoldBug/Controllers/UserAlertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoldBug.Data;
using GoldBug.Models;
using Microsoft.AspNetCore.Mvc;


namespace GoldBug.Controllers
{
	public class UserAlertsController : Controller
	{

		private readonly ApplicationDbContext _db;

		public UserAlertsController(ApplicationDbContext db)
		{
			_db = db;
		}

		[Route("user/myalerts")]
		public IActionResult ViewMyAlerts()
		{
			return View();
		}

		[Route("user/myalerts/init")]
		public IActionResult Init()
		{
			var alertsList = new List<AlertM>();
			alertsList.Add(new AlertM() { Name = "Strona zgłoszona jako niebezpieczna", CriticaLevel = 9, Site = "www.facebook.com" });
			alertsList.Add(new AlertM() { Name = "Strona zawiera treści pornograficzne", CriticaLevel = 6, Site = "www.onet.pl" });
			alertsList.Add(new AlertM() { Name = "Brak protokołu HTTPS", CriticaLevel = 5, Site = "www.itaka.pl" });
			alertsList.Add(new AlertM() { Name = "Brak protokołu HTTPS", CriticaLevel = 5, Site = "www.itaka.pl" });
			alertsList.Add(new AlertM() { Name = "Strona zgłoszona jako niebezpieczna", CriticaLevel = 3, Site = "app.hrappka.pl" });
			alertsList.Add(new AlertM() { Name = "Brak protokołu HTTPS", CriticaLevel = 1, Site = "www.morele.net" });
			alertsList.Add(new AlertM() { Name = "Strona zgłoszona jako niebezpieczna", CriticaLevel = 1, Site = "www.pyszne.pl" });

			foreach (var s in alertsList)
			{
					_db.Add(s);
					_db.SaveChanges();
			}

			return RedirectToAction(nameof(ViewMyAlerts));
		}

		[Route("user/myalerts/update")]
		public IActionResult Update()
		{
			var alertsList = _db.Alerts.ToList();
			foreach (var s in alertsList)
			{
				var site = _db.UserSites.FirstOrDefault(a => a.Domain == s.Site);
				if (site != null)
				{
					s.UserSiteId = site.Id;
					_db.Update(s);
					_db.SaveChanges();
				}

			}
			return RedirectToAction(nameof(ViewMyAlerts));
		}
	}
}

GoldBug/Controllers/UserPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace GoldBug.Controllers
{
    public class UserPanelController : Controller
    {
        [Route("user/dashboard")]
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

GoldBug/Controllers/UserStatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace GoldBug.Controllers
{
    public class UserStatsController : Controller
    {
        
        [Route("user/stats")]
        public IActionResult ViewUserStats()
        {
            return View();
        }
    }
}

GoldBug/Controllers/WordSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoldBug.Data;
using GoldBug.Models;
using Microsoft.AspNetCore.Mvc;

namespace GoldBug.Controllers
{
	public class WordSearchController : Controller
	{
		private readonly ApplicationDbContext _db;

		public WordSearchController(ApplicationDbContext db)
		{
			_db = db;
		}

		[Route("user/my-word-search")]
		public IActionResult MyWordSearch()
		{
			return View();
		}

		[Route("user/my-word-search/init")]
		public IActionResult Init()
		{
			var wordSearchList = new List<WordSearchM>();
			wordSearchList.Add(new WordSearchM() { Site = "www.morele.net", Name = "MSI", Count = 256 });
			wordSearchList.Add(new WordSearchM() { Site = "www.morele.net", Name = "Laptop", Count = 321 });
			wordSearchList.Add(new WordSearchM() { Site = "www.itaka.pl", Name = "Chorwacja", Count = 542 });
			wordSearchList.Add(new WordSearchM() { Site = "www.itaka.pl", Name = "Wakacje", Count = 452 });
			wordSearchList.Add(new WordSearchM() { Site = "www.morele.net", Name = "SSD", Count = 77 });
			wordSearchList.Add(new WordSearchM() { Site = "www.morele.net", Name = "Xiaomi", Count = 153 });
			wordSearchList.Add(new WordSearchM() { Site = "www.pyszne.pl", Name = "Zupa", Count = 40 });
			wordSearchList.Add(new WordSearchM() { Site = "www.itaka.pl", Name = "Grecja", Count = 85 });
			wordSearchList.Add(new WordSearchM() { Site = "www.pyszne.pl", Name = "Lunch", Count = 100 });
			wordSearchList.Add(new WordSearchM() { Site = "www.pyszne.pl", Name = "Proza", Count = 45 });
			wordSearchList.Add(new WordSearchM() { Site = "www.pyszne.pl", Name = "Restaurant", Count = 327 });
			wordSearchList.Add(new WordSearchM() { Site = "www.morele.net", Name = "HDD", Count = 54 });
			wordSearchList.Add(new WordSearchM() { Site = "www.itaka.pl", Name = "Władysławowo", Count = 4 });

			foreach (var s in wordSearchList)
			{
				WordSearchM so = _db.WordSearches.SingleOrDefault(a => a.Name == s.Name);
				if (so == null)
				{
					_db.Add(s);
					_db.SaveChanges();
				}
			}

			return RedirectToAction(nameof(MyWordSearch));
		}

		[Route("user/my-word-search/update")]
		public IActionResult Update()
		{
			var wordSearchList = _db.WordSearches.ToList();
			foreach (var s in wordSearchList)
			{
				var site = _db.UserSites.FirstOrDefault(a => a.Domain == s.Site);
				if (site != null)
				{
					s.UserSiteId = site.Id;
					_db.Update(s);
					_db.SaveChanges();
				}

			}
			return RedirectToAction(nameof(MyWordSearch));
		}
	}
}

GoldBug/Views/Shared/_Sidebar.cshtml
<div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

    <!-- begin:: Aside -->
    <div class="kt-aside__brand kt-grid__item  " id="kt_aside_brand">
        <div class="kt-aside__brand-logo">
            <a href="@Url.Action("Dashboard","UserPanel")">
                <img alt="Logo" src="~/images/logo/logo_png.png" style="width:60px" />
            </a>
        </div>
    </div>

    <!-- end:: Aside -->
    
    <!-- begin:: Aside Menu -->
    <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
        <div id="kt_aside_menu" class="kt-aside-menu  kt-aside-menu--dropdown " data-ktmenu-vertical="1" data-ktmenu-dropdown="1" data-ktmenu-scroll="0">
            <ul class="kt-menu__nav ">

                @if (ViewBag.Route == "dashboard")
                {
                    <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("Dashboard","UserPanel")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-setup"></i><span class="kt-menu__link-text">Dashboard</span></a></li>

                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("Dashboard","UserPanel")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-setup"></i><span class="kt-menu__link-text">Dashboard</span></a></li>
                }

                @if (ViewBag.Route == "mysites")
                {
                    <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("ViewMySties","UserMySites")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-layers"></i><span class="kt-menu__link-text">My Sites</span></a></li>
                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("ViewMySties","UserMySites")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-layers"></i><span class="kt-menu__link-text">My Sites</span></a></li>
                }

                @if (ViewBag.Route == "securityrules")
                {
                    <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("ViewMySecurityRules","UserSecurityRules")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-shield"></i><span class="kt-menu__link-text" style="text-align:center">Security rules</span></a></li>
                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("ViewMySecurityRules","UserSecurityRules")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-shield "></i><span class="kt-menu__link-text" style="text-align:center">Security rules</span></a></li>
                }

                @if (ViewBag.Route == "alerts")
                {
                    <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("ViewMyAlerts","UserAlerts")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-exclamation"></i><span class="kt-menu__link-text">Alerts</span></a></li>
                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("ViewMyAlerts","UserAlerts")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-exclamation "></i><span class="kt-menu__link-text">Alerts</span></a></li>
                }

                @if (ViewBag.Route == "notifications")
                {
                    <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("ViewMyNotifications","UserNotifications")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-notification"></i><span class="kt-menu__link-text">Notifications</span></a></li>
                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("ViewMyNotifications","UserNotifications")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-notification"></i><span class="kt-menu__link-text">Notifications</span></a></li>
                }

                @if (ViewBag.Route == "my-word-search")
                {
                    <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("MyWordSearch","WordSearch")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-search"></i><span class="kt-menu__link-text" style="text-align:center">Word search</span></a></li>
                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("MyWordSearch","WordSearch")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-search"></i><span class="kt-menu__link-text" style="text-align:center">Word search</span></a></li>
                }

                @*<li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
            <a href="javascript:;" class="kt-menu__link kt-menu__toggle"><i class="kt-menu__link-icon flaticon2-layers-1"></i><span class="kt-menu__link-text">Actions</span></a>
            <div class="kt-menu__submenu ">
                <span class="kt-menu__arrow"></span>
                <ul class="kt-menu__subnav">
                    <li class="kt-menu__item  kt-menu__item--parent" aria-haspopup="true"><span class="kt-menu__link"><span class="kt-menu__link-text">Actions</span></span></li>
                    <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-bullet kt-menu__link-bullet--line"><span></span></i><span class="kt-menu__link-text">Add New</span></a></li>
                    <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-bullet kt-menu__link-bullet--line"><span></span></i><span class="kt-menu__link-text">Edit</span></a></li>
                    <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-bullet kt-menu__link-bullet--line"><span></span></i><span class="kt-menu__link-text">Delete</span></a></li>
                    <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-bullet kt-menu__link-bullet--line"><span></span></i><span class="kt-menu__link-text">Import</span></a></li>
                </ul>
            </div>
        </li>*@
                @*<li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-graph"></i><span class="kt-menu__link-text">Reports</span></a></li>
        <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
            <a href="javascript:;" class="kt-menu__link kt-menu__toggle"><i class="kt-menu__link-icon flaticon2-drop"></i><span class="kt-menu__link-text">Config</span></a>
            <div class="kt-menu__submenu ">
                <span class="kt-menu__arrow"></span>
                <ul class="kt-menu__subnav">
                    <li class="kt-menu__item  kt-menu__item--parent" aria-haspopup="true"><span class="kt-menu__link"><span class="kt-menu__link-text">Config</span></span></li>
                    <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i><span class="kt-menu__link-text">Import</span></a></li>
                    <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i><span class="kt-menu__link-text">Backup</span></a></li>
                </ul>
            </div>
        </li>
        <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-analytics-2"></i><span class="kt-menu__link-text">Console</span></a></li>
        <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-protected"></i><span class="kt-menu__link-text">System</span></a></li>
        <li class="kt-menu__item " aria-haspopup="true"><a href="#" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-mail-1"></i><span class="kt-menu__link-text">Logs</span></a></li>*@

                @if (ViewBag.Route == "stats")
                {
                    <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("ViewUserStats","UserStats")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-pie-chart-1"></i><span class="kt-menu__link-text">Stats</span></a></li>
                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("ViewUserStats","UserStats")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon-pie-chart-1"></i><span class="kt-menu__link-text">Stats</span></a></li>
                }

                @if (ViewBag.Route == "settings")
                {
                    <li class="kt-menu__item  kt-menu__item--active" aria-haspopup="true"><a href="@Url.Action("ViewUserSettings","UserSettings")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-gear"></i><span class="kt-menu__link-text">Settings</span></a></li>
                }
                else
                {
                    <li class="kt-menu__item" aria-haspopup="true"><a href="@Url.Action("ViewUserSettings","UserSettings")" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-gear"></i><span class="kt-menu__link-text">Settings</span></a></li>
                }

            </ul>
        </div>
    </div>

    <!-- end:: Aside Menu -->
</div>

GoldBug/Views/Shared/_UserHead.cshtml
<div class="kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x" style="background-image: url(/assets/media/misc/bg-1.jpg)">
    <div class="kt-user-card__avatar">
        <img class="kt-hidden" alt="Pic" src="/assets/media/users/300_25.jpg" />

        <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
        <span class="kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-success">N</span>
    </div>
    <div class="kt-user-card__name">
        Norbert Pisz
    </div>
    <div class="kt-user-card__badge">
        <span class="btn btn-success btn-sm btn-bold btn-font-md">23 messages</span>
    </div>
</div>

<!--begin: Navigation -->
<div class="kt-notification">
    <div class="kt-notification__custom kt-space-between">
        <a href="@Url.Action("Login","Account")" target="_blank" class="btn btn-label btn-label-brand btn-sm btn-bold">Sign Out</a>
    </div>
</div>

<!--end: Navigation -->